// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDROiWDpBl3YUPOrFKbvS9N1wffE1PoM_I',
    appId: '1:498987756899:web:8d4077c1a7fe63013ff756',
    messagingSenderId: '498987756899',
    projectId: 'flutter-chat-app-520f4',
    authDomain: 'flutter-chat-app-520f4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-520f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5exnhGTe_qIyeKXsREWUinlKRFUV1Ef4',
    appId: '1:498987756899:android:0e00433213ec3beb3ff756',
    messagingSenderId: '498987756899',
    projectId: 'flutter-chat-app-520f4',
    storageBucket: 'flutter-chat-app-520f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDALY9jzCGtOp4JQDqfSCS2hOog01mAI78',
    appId: '1:498987756899:ios:73e4edf61752df323ff756',
    messagingSenderId: '498987756899',
    projectId: 'flutter-chat-app-520f4',
    storageBucket: 'flutter-chat-app-520f4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}